// Code generated by counterfeiter. DO NOT EDIT.
package netfakes

import (
	"sync"

	"github.com/cloudfoundry/bosh-agent/v2/platform/net"
)

type FakeInterfaceSelector struct {
	SelectInterfaceStub        func(map[string]string) (string, string, error)
	selectInterfaceMutex       sync.RWMutex
	selectInterfaceArgsForCall []struct {
		arg1 map[string]string
	}
	selectInterfaceReturns struct {
		result1 string
		result2 string
		result3 error
	}
	selectInterfaceReturnsOnCall map[int]struct {
		result1 string
		result2 string
		result3 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeInterfaceSelector) SelectInterface(arg1 map[string]string) (string, string, error) {
	fake.selectInterfaceMutex.Lock()
	ret, specificReturn := fake.selectInterfaceReturnsOnCall[len(fake.selectInterfaceArgsForCall)]
	fake.selectInterfaceArgsForCall = append(fake.selectInterfaceArgsForCall, struct {
		arg1 map[string]string
	}{arg1})
	stub := fake.SelectInterfaceStub
	fakeReturns := fake.selectInterfaceReturns
	fake.recordInvocation("SelectInterface", []interface{}{arg1})
	fake.selectInterfaceMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeInterfaceSelector) SelectInterfaceCallCount() int {
	fake.selectInterfaceMutex.RLock()
	defer fake.selectInterfaceMutex.RUnlock()
	return len(fake.selectInterfaceArgsForCall)
}

func (fake *FakeInterfaceSelector) SelectInterfaceCalls(stub func(map[string]string) (string, string, error)) {
	fake.selectInterfaceMutex.Lock()
	defer fake.selectInterfaceMutex.Unlock()
	fake.SelectInterfaceStub = stub
}

func (fake *FakeInterfaceSelector) SelectInterfaceArgsForCall(i int) map[string]string {
	fake.selectInterfaceMutex.RLock()
	defer fake.selectInterfaceMutex.RUnlock()
	argsForCall := fake.selectInterfaceArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeInterfaceSelector) SelectInterfaceReturns(result1 string, result2 string, result3 error) {
	fake.selectInterfaceMutex.Lock()
	defer fake.selectInterfaceMutex.Unlock()
	fake.SelectInterfaceStub = nil
	fake.selectInterfaceReturns = struct {
		result1 string
		result2 string
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeInterfaceSelector) SelectInterfaceReturnsOnCall(i int, result1 string, result2 string, result3 error) {
	fake.selectInterfaceMutex.Lock()
	defer fake.selectInterfaceMutex.Unlock()
	fake.SelectInterfaceStub = nil
	if fake.selectInterfaceReturnsOnCall == nil {
		fake.selectInterfaceReturnsOnCall = make(map[int]struct {
			result1 string
			result2 string
			result3 error
		})
	}
	fake.selectInterfaceReturnsOnCall[i] = struct {
		result1 string
		result2 string
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeInterfaceSelector) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeInterfaceSelector) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ net.InterfaceSelector = new(FakeInterfaceSelector)
