// Code generated by counterfeiter. DO NOT EDIT.
package netfakes

import (
	"sync"

	"github.com/cloudfoundry/bosh-agent/v2/platform/net"
)

type FakeInterfaceDriverDetector struct {
	DetectInterfaceDriverStub        func(string) (string, error)
	detectInterfaceDriverMutex       sync.RWMutex
	detectInterfaceDriverArgsForCall []struct {
		arg1 string
	}
	detectInterfaceDriverReturns struct {
		result1 string
		result2 error
	}
	detectInterfaceDriverReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	IsSyntheticInterfaceStub        func(string) (bool, error)
	isSyntheticInterfaceMutex       sync.RWMutex
	isSyntheticInterfaceArgsForCall []struct {
		arg1 string
	}
	isSyntheticInterfaceReturns struct {
		result1 bool
		result2 error
	}
	isSyntheticInterfaceReturnsOnCall map[int]struct {
		result1 bool
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeInterfaceDriverDetector) DetectInterfaceDriver(arg1 string) (string, error) {
	fake.detectInterfaceDriverMutex.Lock()
	ret, specificReturn := fake.detectInterfaceDriverReturnsOnCall[len(fake.detectInterfaceDriverArgsForCall)]
	fake.detectInterfaceDriverArgsForCall = append(fake.detectInterfaceDriverArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.DetectInterfaceDriverStub
	fakeReturns := fake.detectInterfaceDriverReturns
	fake.recordInvocation("DetectInterfaceDriver", []interface{}{arg1})
	fake.detectInterfaceDriverMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeInterfaceDriverDetector) DetectInterfaceDriverCallCount() int {
	fake.detectInterfaceDriverMutex.RLock()
	defer fake.detectInterfaceDriverMutex.RUnlock()
	return len(fake.detectInterfaceDriverArgsForCall)
}

func (fake *FakeInterfaceDriverDetector) DetectInterfaceDriverCalls(stub func(string) (string, error)) {
	fake.detectInterfaceDriverMutex.Lock()
	defer fake.detectInterfaceDriverMutex.Unlock()
	fake.DetectInterfaceDriverStub = stub
}

func (fake *FakeInterfaceDriverDetector) DetectInterfaceDriverArgsForCall(i int) string {
	fake.detectInterfaceDriverMutex.RLock()
	defer fake.detectInterfaceDriverMutex.RUnlock()
	argsForCall := fake.detectInterfaceDriverArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeInterfaceDriverDetector) DetectInterfaceDriverReturns(result1 string, result2 error) {
	fake.detectInterfaceDriverMutex.Lock()
	defer fake.detectInterfaceDriverMutex.Unlock()
	fake.DetectInterfaceDriverStub = nil
	fake.detectInterfaceDriverReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeInterfaceDriverDetector) DetectInterfaceDriverReturnsOnCall(i int, result1 string, result2 error) {
	fake.detectInterfaceDriverMutex.Lock()
	defer fake.detectInterfaceDriverMutex.Unlock()
	fake.DetectInterfaceDriverStub = nil
	if fake.detectInterfaceDriverReturnsOnCall == nil {
		fake.detectInterfaceDriverReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.detectInterfaceDriverReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeInterfaceDriverDetector) IsSyntheticInterface(arg1 string) (bool, error) {
	fake.isSyntheticInterfaceMutex.Lock()
	ret, specificReturn := fake.isSyntheticInterfaceReturnsOnCall[len(fake.isSyntheticInterfaceArgsForCall)]
	fake.isSyntheticInterfaceArgsForCall = append(fake.isSyntheticInterfaceArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.IsSyntheticInterfaceStub
	fakeReturns := fake.isSyntheticInterfaceReturns
	fake.recordInvocation("IsSyntheticInterface", []interface{}{arg1})
	fake.isSyntheticInterfaceMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeInterfaceDriverDetector) IsSyntheticInterfaceCallCount() int {
	fake.isSyntheticInterfaceMutex.RLock()
	defer fake.isSyntheticInterfaceMutex.RUnlock()
	return len(fake.isSyntheticInterfaceArgsForCall)
}

func (fake *FakeInterfaceDriverDetector) IsSyntheticInterfaceCalls(stub func(string) (bool, error)) {
	fake.isSyntheticInterfaceMutex.Lock()
	defer fake.isSyntheticInterfaceMutex.Unlock()
	fake.IsSyntheticInterfaceStub = stub
}

func (fake *FakeInterfaceDriverDetector) IsSyntheticInterfaceArgsForCall(i int) string {
	fake.isSyntheticInterfaceMutex.RLock()
	defer fake.isSyntheticInterfaceMutex.RUnlock()
	argsForCall := fake.isSyntheticInterfaceArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeInterfaceDriverDetector) IsSyntheticInterfaceReturns(result1 bool, result2 error) {
	fake.isSyntheticInterfaceMutex.Lock()
	defer fake.isSyntheticInterfaceMutex.Unlock()
	fake.IsSyntheticInterfaceStub = nil
	fake.isSyntheticInterfaceReturns = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeInterfaceDriverDetector) IsSyntheticInterfaceReturnsOnCall(i int, result1 bool, result2 error) {
	fake.isSyntheticInterfaceMutex.Lock()
	defer fake.isSyntheticInterfaceMutex.Unlock()
	fake.IsSyntheticInterfaceStub = nil
	if fake.isSyntheticInterfaceReturnsOnCall == nil {
		fake.isSyntheticInterfaceReturnsOnCall = make(map[int]struct {
			result1 bool
			result2 error
		})
	}
	fake.isSyntheticInterfaceReturnsOnCall[i] = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeInterfaceDriverDetector) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeInterfaceDriverDetector) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ net.InterfaceDriverDetector = new(FakeInterfaceDriverDetector)
